# Generated by Django 3.2.6 on 2021-08-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('lobby_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('like', models.CharField(max_length=64)),
                ('dislike', models.CharField(max_length=64)),
                ('points', models.PositiveIntegerField(default=0)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likes_and_dislikes.lobby')),
            ],
            options={
                'ordering': ['points', 'nickname'],
            },
        ),
    ]
