# Generated by Django 3.2.6 on 2021-08-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_and_dislikes', '0003_rename_likes_card_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='likes_and_dislikes.player'),
        ),
    ]
