# Generated by Django 3.2.6 on 2021-08-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_and_dislikes', '0004_alter_card_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='likes_and_dislikes.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='likes_and_dislikes.lobby'),
        ),
    ]
