# Generated by Django 3.2.6 on 2021-08-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_and_dislikes', '0006_auto_20210821_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['pk']},
        ),
    ]
