# Generated by Django 3.2.6 on 2021-08-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_and_dislikes', '0007_alter_card_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='current_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='game_has_started',
            field=models.BooleanField(default=False),
        ),
    ]
